[package]
name = "sorting_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sdl2 = {version = "*", default-features = false, features = ["ttf"]}
rand = "0.8.5"